### ISSUE TITLE
Allow for non-interactive use

### ISSUE THREAD

**Issue by knuesel** [devmotion/PalmerPenguins.jl#9]
It took me a while to figure out why my notebook was not executing properly: a cell was stuck showing an "stdin" input box. It turns out that `PalmerPenguins.load()` was waiting for user input to download the dataset.

Is this necessary? I expected the data to be downloaded silently. It seems to me that installing the PalmerPenguins package says clearly that I want to install the data. Asking for confirmation during the program executing seems like needless friction...

For context, I'm preparing a script for PackageCompiler to make a sysimage. I wanted to include a tutorial that uses the PalmerPenguins data as typical code that should be precompiled. The script should be executable in a new Julia installation without user input, but I'm not sure how to do that given this confirmation prompt.

**Comment by klaff** [comment]
Using `ENV["DATADEPS_ALWAYS_ACCEPT"] = true` prior to loading the dataset may work.

See https://www.oxinabox.net/DataDeps.jl/stable/z40-apiref/#DataDeps.register
